workflows:
  ios-iap-release:
    name: Dare to Connect iOS IAP Release
    integrations:
      app_store_connect: codemagic-key 
    
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        NODE_VERSION: "20.x"
        COCOAPODS_VERSION: "1.15.2"
        DEVELOPMENT_TEAM: "H9A4H444G4" 
        BUNDLE_ID: "daretoconnect.app.mobile"
        APP_VERSION: "2.3" 
        CI: "false"
        DISABLE_ESLINT_PLUGIN: "true"
        REVENUECAT_IOS_API_KEY: "${REVENUECAT_IOS_API_KEY}"  # Will be in groups
      groups:
        - DareToConnect
        - revenuecat_keys  # RevenueCat API keys
      node: 20
      xcode: latest

    cache:
      cache_paths:
        - ~/.npm
        - node_modules
        - ios/Pods

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
        - pattern: release/*
          include: true

    scripts:
      # PHASE 1: CLEAN WORKSPACE
      - name: Clean Workspace
        script: |
          echo "=== Cleaning Workspace ==="
          rm -rf node_modules ios/Pods ios/App/Pods
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          rm -rf ios/Pods ios/Podfile.lock
          npm cache clean --force
          echo "✅ Workspace cleaned"

      # PHASE 2: INSTALL DEPENDENCIES
      - name: Install Dependencies
        script: |
          set -ex
          echo "=== Installing Node Modules ==="
          npm ci || npm install
          
          echo "=== Verifying RevenueCat installation ==="
          if [ -d "node_modules/@revenuecat/purchases-capacitor" ]; then
            echo "✅ @revenuecat/purchases-capacitor installed"
          else
            echo "Installing RevenueCat..."
            npm install @revenuecat/purchases-capacitor@12.1.1
          fi

      # PHASE 3: BUILD REACT APP
      - name: Build React App
        script: |
          set -ex
          echo "=== Building React App ==="
          export DISABLE_ESLINT_PLUGIN=true
          export ESLINT_NO_DEV_ERRORS=false
          export GENERATE_SOURCEMAP=false
          
          npm run build
          
          if [ ! -d "build" ]; then
            echo "❌ React build failed"
            exit 1
          fi
          echo "✅ React build completed"

      # PHASE 4: CAPACITOR SYNC
      - name: Sync Capacitor
        script: |
          set -ex
          echo "=== Syncing Capacitor ==="
          
          # Add iOS platform if needed
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
          
          # Sync everything
          npx cap sync ios
          
          echo "✅ Capacitor sync complete"

      # PHASE 5: CONFIGURE INFO.PLIST FOR IAP
      - name: Configure IAP in Info.plist
        script: |
          set -ex
          echo "=== Configuring IAP Settings ==="
          cd ios/App/App
          PLIST_PATH="Info.plist"
          
          # Add Privacy Policy URL
          /usr/libexec/PlistBuddy -c "Add :PrivacyPolicyURL string https://www.daretoconnectgames.com/privacy" "$PLIST_PATH" 2>/dev/null || \
          /usr/libexec/PlistBuddy -c "Set :PrivacyPolicyURL https://www.daretoconnectgames.com/privacy" "$PLIST_PATH"
          
          # Add Terms of Use URL (Apple's standard EULA)
          /usr/libexec/PlistBuddy -c "Add :TermsOfUseURL string https://www.apple.com/legal/internet-services/itunes/dev/stdeula/" "$PLIST_PATH" 2>/dev/null || \
          /usr/libexec/PlistBuddy -c "Set :TermsOfUseURL https://www.apple.com/legal/internet-services/itunes/dev/stdeula/" "$PLIST_PATH"
          
          # Add encryption compliance
          /usr/libexec/PlistBuddy -c "Add :ITSAppUsesNonExemptEncryption bool false" "$PLIST_PATH" 2>/dev/null || \
          /usr/libexec/PlistBuddy -c "Set :ITSAppUsesNonExemptEncryption false" "$PLIST_PATH"
          
          # Add microphone usage description
          /usr/libexec/PlistBuddy -c "Add :NSMicrophoneUsageDescription string 'Used for voice recording in games and activities'" "$PLIST_PATH" 2>/dev/null || \
          /usr/libexec/PlistBuddy -c "Set :NSMicrophoneUsageDescription 'Used for voice recording in games and activities'" "$PLIST_PATH"
          
          echo "✅ IAP configuration complete"

      # PHASE 6: UPDATE VERSION NUMBERS
      - name: Update Version Numbers
        script: |
          set -ex
          echo "=== Updating Version Numbers ==="
          cd ios/App/App
          PLIST_PATH="Info.plist"
          
          # Generate build number (timestamp)
          BUILD_NUMBER=$(date +%s)
          
          # Set version and build
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $APP_VERSION" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" "$PLIST_PATH"
          
          echo "Version: $APP_VERSION"
          echo "Build: $BUILD_NUMBER"
          echo "Bundle ID: $BUNDLE_ID"
          echo "✅ Version numbers updated"

      # PHASE 7: IOS PROJECT CONFIGURATION
      - name: Configure iOS Project
        script: |
          set -ex
          echo "=== Configuring iOS Project ==="
          cd ios/App
          
          # Update Podfile for iOS 15.0
          if [ -f "Podfile" ]; then
            sed -i.bak "s/platform :ios, .*/platform :ios, '15.0'/g" Podfile
            rm -f Podfile.bak
          fi
          
          # Install pods
          pod install --repo-update
          
          # Configure Swift settings in project.pbxproj
          PBXPROJ="App.xcodeproj/project.pbxproj"
          if [ -f "$PBXPROJ" ]; then
            # Set deployment target
            sed -i.bak 's/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' "$PBXPROJ"
            
            # Set Swift version
            sed -i.bak 's/SWIFT_VERSION = .*/SWIFT_VERSION = 5.0;/g' "$PBXPROJ"
            
            # Ensure Swift libraries are embedded
            sed -i.bak 's/ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = .*/ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES;/g' "$PBXPROJ"
            
            rm -f "$PBXPROJ.bak"
          fi
          
          echo "✅ iOS project configured"

      # PHASE 8: CODE SIGNING SETUP
      - name: Configure Code Signing
        script: |
          set -ex
          echo "=== Setting Up Code Signing ==="
          cd ios/App
          
          # Import certificate
          echo "$CERTIFICATE" | base64 --decode > /tmp/certificate.p12
          
          # Import provisioning profile
          echo "$PROVISIONING_PROFILE" | base64 --decode > /tmp/profile.mobileprovision
          
          # Extract UUID from profile (using openssl since security not available)
          PROFILE_UUID=$(openssl smime -inform der -verify -noverify -in /tmp/profile.mobileprovision 2>/dev/null | \
                        grep -A1 '<key>UUID</key>' | grep '<string>' | sed -E 's/.*<string>(.*)<\/string>.*/\1/')
          
          if [ -z "$PROFILE_UUID" ]; then
            echo "❌ Failed to extract profile UUID"
            exit 1
          fi
          
          # Set up keychain
          keychain initialize
          
          # Add certificate to keychain
          keychain add-certificates \
            --certificate /tmp/certificate.p12 \
            --certificate-password "$CERTIFICATE_PASSWORD"
          
          # Install provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/"$PROFILE_UUID".mobileprovision
          
          # Set up code signing settings
          xcode-project use-profiles
          
          echo "PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV
          echo "✅ Code signing configured"

      # PHASE 9: BUILD IPA
      - name: Build IPA
        script: |
          set -ex
          echo "=== Building IPA ==="
          cd ios/App
          
          # Build the IPA
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --configuration Release
          
          if [ ! -f "build/ios/ipa/App.ipa" ]; then
            echo "❌ IPA build failed"
            exit 1
          fi
          
          echo "✅ IPA built successfully"

      # PHASE 10: VALIDATE BUILD
      - name: Validate Build
        script: |
          set -ex
          echo "=== Validating Build ==="
          
          IPA_PATH="ios/App/build/ios/ipa/App.ipa"
          if [ ! -f "$IPA_PATH" ]; then
            echo "❌ IPA file not found"
            exit 1
          fi
          
          echo "✅ Build validation complete"
          echo "IPA size: $(du -h $IPA_PATH | cut -f1)"

    artifacts:
      - ios/App/build/ios/ipa/App.ipa
      - ios/App/App/Info.plist
      - build_info.txt

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "Internal Testers"
        beta_app_feedback_email: "feedback@daretoconnectgames.com"
      
      email:
        recipients:
          - "your-email@example.com"
        notify:
          - success
          - failure